-- 1º consulta 
SELECT I.NOMBRE AS INSTITUTO, SUM(LP.CANTIDAD) AS TOTAL_PRODUCTOS_VENDIDOS 
FROM INSTITUTOS I 
INNER JOIN BUFFALOS B ON I.ID_INSTITUTO = B.ID_INSTITUTO 
INNER JOIN PEDIDOS PE ON B.ID_PERSONA = PE.ID_PERSONA 
INNER JOIN LINEADEPEDIDOS LP ON PE.ID_PEDIDO = LP.ID_PEDIDO 
GROUP BY I.NOMBRE;

-- 2º consulta
SELECT A.NOMBRE AS ACTIVIDAD, COUNT(MA.ID_PERSONA) AS CANTIDAD_MONITORES 
FROM ACTIVIDADES A 
LEFT JOIN MONITORESACTIVIDADES MA ON A.ID_ACTIVIDAD = MA.ID_ACTIVIDAD 
GROUP BY A.NOMBRE;

-- 3º consulta
SELECT I.NOMBRE AS INSTITUTO, AVG(P.PRECIO) AS PRECIO_PROMEDIO_PAQUETE 
FROM INSTITUTOS I
INNER JOIN PAQUETES P ON I.ID_PAQUETE = P.ID_PAQUETE 
GROUP BY I.NOMBRE 
ORDER BY PRECIO_PROMEDIO_PAQUETE 
DESC LIMIT 1;

-- 4º consulta
SELECT DISTINCT P.NOMBRE, P.APELLIDOS 
FROM PERSONAS P 
INNER JOIN MONITORES M ON P.ID_PERSONA = M.ID_PERSONA 
INNER JOIN PEDIDOS PE ON P.ID_PERSONA = PE.ID_PERSONA 
INNER JOIN LINEADEPEDIDOS LP ON PE.ID_PEDIDO = LP.ID_PEDIDO 
INNER JOIN PRODUCTOS PR ON LP.ID_PRODUCTO = PR.ID_PRODUCTO 
WHERE PR.PRECIOPVP > (SELECT AVG(PRECIOPVP) FROM PRODUCTOS);

-- 5º consulta
SELECT I.NOMBRE AS INSTITUTO, COUNT(PE.ID_PEDIDO) AS CANTIDAD_PEDIDOS 
FROM INSTITUTOS I 
INNER JOIN BUFFALOS B ON I.ID_INSTITUTO = B.ID_INSTITUTO 
INNER JOIN PEDIDOS PE ON B.ID_PERSONA = PE.ID_PERSONA 
WHERE MONTH(PE.FECHAPEDIDO) = 3 -- Cambiar el número del mes según 
-- corresponda 
GROUP BY I.NOMBRE 
ORDER by CANTIDAD_PEDIDOS 
DESC LIMIT 1;