DROP TABLE ACTIVIDADESPAQUETES;
DROP TABLE MONITORESACTIVIDADES;
DROP TABLE ACTIVIDADES;
DROP TABLE LINEADEPEDIDOS;
DROP TABLE PEDIDOS;
DROP TABLE PRODUCTOS;
DROP TABLE BUFFALOS;
DROP TABLE MONITORES;
DROP TABLE PERSONAS;
DROP TABLE INSTITUTOS;
DROP TABLE PAQUETES;

CREATE TABLE PERSONAS(
ID_PERSONA NUMBER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDOS VARCHAR2(100) NOT NULL,
DNI VARCHAR2(9) NOT NULL,
FECHANACIMIENTO DATE NOT NULL
CHECK(FECHANACIMIENTO<to_date('12/12/2013','DD/MM/RR')),
TELEFONO VARCHAR2(9),
EMAIL VARCHAR2(100),
DIRECCION VARCHAR2(200) NOT NULL,
TIPOPERSONA VARCHAR2(50) CHECK (TIPOPERSONA IN('Monitor','Buffalo')),
PRIMARY KEY(ID_PERSONA));

CREATE TABLE PAQUETES(
ID_PAQUETE NUMBER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
DESCRIPCION VARCHAR2(250) NOT NULL,
PRECIO FLOAT NOT NULL CHECK(PRECIO>0),
PRIMARY KEY(ID_PAQUETE));

CREATE TABLE INSTITUTOS(
ID_INSTITUTO NUMBER NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
DIRECCION VARCHAR2(250) NOT NULL,
CODPOSTAL VARCHAR2(5) NOT NULL,
ID_PAQUETE NUMBER NOT NULL,
PRIMARY KEY(ID_INSTITUTO),
FOREIGN KEY(ID_PAQUETE) REFERENCES PAQUETES ON DELETE CASCADE);

CREATE TABLE ACTIVIDADES(
ID_ACTIVIDAD NUMBER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
DESCRIPCION VARCHAR2(250) NOT NULL,
TIEMPO NUMBER,
PRIMARY KEY(ID_ACTIVIDAD));

CREATE TABLE ACTIVIDADESPAQUETES(
ID_ACTIVIDAD NUMBER NOT NULL,
ID_PAQUETE NUMBER NOT NULL,
PRIMARY KEY(ID_ACTIVIDAD,ID_PAQUETE),
FOREIGN KEY(ID_ACTIVIDAD) REFERENCES ACTIVIDADES ON DELETE CASCADE,
FOREIGN KEY(ID_PAQUETE) REFERENCES PAQUETES ON DELETE CASCADE);

CREATE TABLE MONITORES(
ID_PERSONA NUMBER NOT NULL,
TIPOMONITOR VARCHAR2(100) NOT NULL CHECK (TIPOMONITOR
IN('Jefe','Normal','Becario')),
PRIMARY KEY(ID_PERSONA),
FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS ON DELETE CASCADE);

CREATE TABLE BUFFALOS(
ID_PERSONA NUMBER NOT NULL,
ID_INSTITUTO NUMBER NOT NULL,
TIPOBUFFALO VARCHAR2(100) NOT NULL CHECK(TIPOBUFFALO
IN('Alumno','Profesor')),
PRIMARY KEY(ID_PERSONA),
FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS ON DELETE CASCADE,
FOREIGN KEY(ID_INSTITUTO) REFERENCES INSTITUTOS ON DELETE CASCADE);

CREATE TABLE MONITORESACTIVIDADES(
ID_PERSONA NUMBER NOT NULL,
ID_ACTIVIDAD NUMBER NOT NULL,
PRIMARY KEY(ID_PERSONA,ID_ACTIVIDAD),
FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS ON DELETE CASCADE,
FOREIGN KEY(ID_ACTIVIDAD) REFERENCES ACTIVIDADES ON DELETE CASCADE);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO NUMBER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
DESCRIPCION VARCHAR2(250) NOT NULL,
PRECIOPVP FLOAT CHECK(PRECIOPVP >0.0),
PRECIOINSTITUTO FLOAT CHECK(PRECIOINSTITUTO >0.0),
PRIMARY KEY(ID_PRODUCTO));

CREATE TABLE PEDIDOS(
ID_PEDIDO NUMBER NOT NULL,
ID_PERSONA NUMBER NOT NULL,
FECHAPEDIDO DATE NOT NULL,
PRIMARY KEY(ID_PEDIDO),
FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS ON DELETE CASCADE);

CREATE TABLE LINEADEPEDIDOS(
ID_PRODUCTO NUMBER NOT NULL,
ID_PEDIDO NUMBER NOT NULL,
CANTIDAD NUMBER NOT NULL CHECK(CANTIDAD>0),
PRECIO FLOAT NOT NULL CHECK(PRECIO>0.0),
PRIMARY KEY(ID_PRODUCTO,ID_PEDIDO),
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS ON DELETE CASCADE,
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS ON DELETE CASCADE);

