DROP TABLE ACTIVIDADESPAQUETES;
DROP TABLE MONITORESACTIVIDADES;
DROP TABLE ACTIVIDADES;
DROP TABLE LINEADEPEDIDOS;
DROP TABLE PEDIDOS;
DROP TABLE PRODUCTOS;
DROP TABLE BUFFALOS;
DROP TABLE MONITORES;
DROP TABLE PERSONAS;
DROP TABLE INSTITUTOS;
DROP TABLE PAQUETES;

CREATE DATABASE BUFFALOS;

USE BUFFALOS;

CREATE TABLE PERSONAS(
ID_PERSONA INT NOT null,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(100) NOT NULL,
DNI VARCHAR(9) NOT NULL,
FECHANACIMIENTO DATE NOT null,
TELEFONO VARCHAR(9),
EMAIL VARCHAR(100),
DIRECCION VARCHAR(200) NOT NULL,
TIPOPERSONA VARCHAR(50) CHECK (TIPOPERSONA IN('Monitor','Buffalo')),
PRIMARY KEY(ID_PERSONA));

CREATE TABLE PAQUETES(
ID_PAQUETE INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(250) NOT NULL,
PRECIO FLOAT NOT NULL CHECK(PRECIO>0),
PRIMARY KEY(ID_PAQUETE));

CREATE TABLE INSTITUTOS(
ID_INSTITUTO INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
DIRECCION VARCHAR(250) NOT NULL,
CODPOSTAL VARCHAR(5) NOT NULL,
ID_PAQUETE INT NOT NULL,
PRIMARY KEY(ID_INSTITUTO),
FOREIGN KEY(ID_PAQUETE) REFERENCES paquetes(ID_PAQUETE) ON DELETE CASCADE);


CREATE TABLE ACTIVIDADES(
ID_ACTIVIDAD INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(250) NOT NULL,
TIEMPO INT,
PRIMARY KEY(ID_ACTIVIDAD));

CREATE TABLE ACTIVIDADESPAQUETES(
ID_ACTIVIDAD INT NOT NULL,
ID_PAQUETE INT NOT NULL,
PRIMARY KEY(ID_ACTIVIDAD,ID_PAQUETE),
FOREIGN KEY(ID_ACTIVIDAD) REFERENCES ACTIVIDADES(ID_ACTIVIDAD)ON DELETE CASCADE,
FOREIGN KEY(ID_PAQUETE) REFERENCES PAQUETES (ID_PAQUETE)ON DELETE CASCADE);

CREATE TABLE MONITORES(
ID_PERSONA INT NOT NULL,
TIPOMONITOR VARCHAR(100) NOT NULL CHECK (TIPOMONITOR
IN('Jefe','Normal','Becario')),
PRIMARY KEY(ID_PERSONA),
FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE);

CREATE TABLE BUFFALOS(
ID_PERSONA INT NOT NULL,
ID_INSTITUTO INT NOT NULL,
TIPOBUFFALO VARCHAR(100) NOT NULL CHECK(TIPOBUFFALO
IN('Alumno','Profesor')),
PRIMARY KEY(ID_PERSONA),
FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE,
FOREIGN KEY(ID_INSTITUTO) REFERENCES INSTITUTOS(ID_INSTITUTO) ON DELETE CASCADE);

CREATE TABLE MONITORESACTIVIDADES(
ID_PERSONA INT NOT NULL,
ID_ACTIVIDAD INT NOT NULL,
PRIMARY KEY(ID_PERSONA,ID_ACTIVIDAD),
FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE,
FOREIGN KEY(ID_ACTIVIDAD) REFERENCES ACTIVIDADES(ID_ACTIVIDAD) ON DELETE CASCADE);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(250) NOT NULL,
PRECIOPVP FLOAT CHECK(PRECIOPVP >0.0),
PRECIOINSTITUTO FLOAT CHECK(PRECIOINSTITUTO >0.0),
PRIMARY KEY(ID_PRODUCTO));

CREATE TABLE PEDIDOS(
ID_PEDIDO INT NOT NULL,
ID_PERSONA INT NOT NULL,
FECHAPEDIDO DATE NOT NULL,
PRIMARY KEY(ID_PEDIDO),
FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE);

CREATE TABLE LINEADEPEDIDOS(
ID_PRODUCTO INT NOT NULL,
ID_PEDIDO INT NOT NULL,
CANTIDAD INT NOT NULL CHECK(CANTIDAD>0),
PRECIO FLOAT NOT NULL CHECK(PRECIO>0.0),
PRIMARY KEY(ID_PRODUCTO,ID_PEDIDO),
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO) ON DELETE CASCADE,
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO) ON DELETE CASCADE);
